name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy to Yechan Runner

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: List files for debugging
      run: ls -al

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
