# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy to Self-Hosted Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy to Yechan Runner
    defaults:
      run:
        working-directory: /home/yechan/app/

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main
